config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :products
  resources :reviews
  resources :products

  root 'top#pre_search'
  get '/products/:id' => 'products#show'
  get '/link/:id' => 'top#link'

  post '/entry/:product_id' => 'top#post'
  get '/entry/:id' => 'top#entry'

  get '/search' => 'top#search'
  get '/list' => 'products#show_professer'
  get '/easy' => 'top#easy'
  get '/fun' => 'top#fun'
  get '/pre_search' =>'top#pre_search'
  get '/pre_search_review' =>'top#pre_search_review'
  get '/pre_search_entry' => 'top#pre_search_entry'
  get '/pre_search_test' => 'top#pre_search_test'
  get '/search_2' => 'top#search_2'
  get '/search_3' => 'top#search_3'
  get '/search_4' => 'top#search_4'
  get '/users/sign_out' => 'devise/sessions#destroy'
  get '/reviews/:id/edit' => 'top#edit'
  get '/thank_you' => 'top#thank_you'

  post '/test/:product_id' => 'tests#create'
  get '/test/:id' => 'tests#set_product'
  get 'show/test/:id' => 'tests#show'
  get '/show/:id' => 'top#show'
  get '/test/:id/image' => 'tests#show_image'
  get '/tests/index' => 'tests#index'
  get '/thank_you' => 'tests#thank_you'

   resources :tests

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

   def index
    product_ids = Review.group(:product_id).order('count_product_id DESC').limit(20).count(:product_id).keys
    @ranking = product_ids.map { |id| Product.find(id)}
  end

  def easy
    @ranking = Review.all.order('easy DESC').limit(20)
  end

  def fun 
    @ranking = Review.all.order('fun DESC').limit(20)
  end

  def link
    @product = Product.find(params[:id])
  end

  def error
  end

  def pre_search
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

  def pre_search_review
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

  def pre_search_entry
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

  def search_2
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

  def search_3
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

  def search_4
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end


  def edit
  end

  def pre_search_test
     @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end


  def show 
    @product = Product.find(params[:id])
  end



def thank_you 
end

  def post
   @review = current_user.reviews.create(create_params)
   if @review.save
   redirect_to action: "thank_you"
 elsif @review
  redirect_to action: "post"
  flash[:notice] =  "✴︎コメントは最低でも１文字以上お書きください"
end
 end


  def entry
    @product = Product.find(entry_params[:id])
  end

   def review
    @product = Product.find(entry_params[:id])
  end

  def search
    @products = Product.where('title LIKE(?)', "%#{search_params[:keyword]}%").page(params[:page])
  end

private
  def entry_params
    params.permit(:id)
  end

  def search_params
    params.permit(:keyword)
  end

  def create_params
    params.permit(:report, :attendence, :test, :review, :easy, :fun, :product_id)
  end

end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/error.html.erb
<header class = "top clearfix">
   C-Campas
  <div class = "search">
    <%= form_tag("/search", method: :get) do %>
    <input class="search__query" name="keyword" placeholder="授業名で検索" type="text" value="">
    <button class="btn-search" title="検索" type="submit"><i class="icon-search">検索</i></button>
    <% end %>
  </div>

</header>
  <a href ="/">ランキングに戻る</a></div>
 <a href ="/">授業を検索する</a>

<p>レビューの保存に失敗しました。全ての質問にお答えください。</p>
<a href ="">レビューをやり直す</a>

app/views/top/review.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href ="/assets/css/reset.css" rel ="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>

<style>
body {margin: 0 auto;}
body {text-align: center;}
strong{color: white;}
strong{font-size: 18px;}
strong{display: inline-table;}
.header {padding-top: 30px;}
.header {background-color: yellowgreen;}
.header {height:50px;}


.green_box {width: 200px;}
.green_box {height:30px;}
.green_box {background-color: green;}
.green_box {color: white;}
.green_box {font-size: 18px;}
.green_box {margin: 0 auto;}




#write {color: pink}
#write {border-bottom: 2px ridge orange;}
.main1 {padding-top: 30px;}





</style>



<script>

function validate(f)
{
  if(f.easy.value == "") 
  {
    alert("楽単度を入力してください");
    return false;
  }
  else if(f.fun.value =="");
  {
    alert("面白さを入力してください");
    return false;
  }
  else if(f.report.value =="");
  {
    alert("レポートの有無を入力してください");
    return false;
  }
  else if(f.attendence.value == "")
  {
    alert("出席の有無を入力してください");
    return false;
  }
  else if(f.test.value =="")
  {
    alert("テストの有無を入力してください");
    return false;
  }
  else if(f.review.value =="")
    alert("コメントを何かお書きください");
    return false;
  }
  return true;
}








</script>


<div class ="header">

  <strong id ="fun">充実度ランキング</strong>　　<strong id ="easy">楽単度ランキング</strong>　　<a href ="/"><strong id ="index">注目授業ランキング</strong></a>　　<a href ="/pre_search"><strong id ="search">授業を検索</strong></a>　　<a href ="/pre_search_review"><strong id ="review">授業評価を見る</strong></a>　　<a href ="/pre_search_entry"><strong id ="write">授業評価を書く</strong></a>　<% if user_signed_in? %> <a href ="/users/sign_out"><strong id ="logout">ログアウト</strong></a> <% else %> <a href ="/users/sign_up"><strong id ="sign_up">新規登録</strong></a>　　<a href ="/users/sign_in"><strong id ="sign_up">ログイン</strong>
  <% end %>
  </div>

<div class ="main1 clearfix">
  <div class ="title1">
    <h3>科目名 : <%= @product.title %></h3>
  </div>
  <div class ="professer">
    <h3>担当教員 : <%= @product.professer %></h3>
  </div>
<!-- <form action="entry/<%= @product_id %>" method="post"> -->

  <%= form_tag("/entry/#{@product.id}", :method => :post ) do %>
   <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>エラーが発生しました。</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class = "info clearfix">

<!--       <div class ="info clearfix"> -->
        <label class = "easy_1" style="margin-right: 8px">
          <strong>楽単度</strong>
        </label>

        <input class="search__query1" name="easy" placeholder="楽単度" style="text-align: right" type="number" max="5" min="1" value="1"> (5段階評価でお選びください)


      <label class="right_search"style="margin-right: 8px">
        <strong>面白さ</strong>
      </label>


      <input class="search__query2 " name="fun" placeholder="面白さ" style="text-align: right" type="number" max="5" min="1" value="1"> (5段階評価でお選びください)


    </div>

    <div class ="detail">
      <div class ="report">レポートの有無
        <input type="radio" name="report" value="1">有
        <input type="radio" name="report" value="0">無
      </div>
      <div class = "attendence clearfix">出欠の有無
        <input type="radio" name="attendence" value="1">毎回取る
        <input type="radio" name="attendence" value="0">取らない
      </div>
      <div class = "test">テストの有無
        <input type="radio" name="test" value="1">有
        <input type="radio" name="test" value="0">無 
      </div>
    </div>
    <input type="hidden" name="product_id" value="<%= @product.id %>">
    <textarea class="textbox1" placeholder="ここからお書きください" name="review"></textarea>
    <input class = "send"type="submit" value="送信する">
<!-- </form> -->
</form>
  <% end %>
 
</div>

<h4 id ="aaa"><div class ="green_box"><p><%= link_to '検索画面に戻る', pre_search_path, :style=>"color:white;" %></p></h4></div>

 <h4 id ="aaa"><div class ="green_box"><p><%= link_to 'ランキングへ', root_path, :style=>"color:white;" %></p></h4></div>


  <footer>
  </footer>

  <script>


$(function(){

  $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#fun').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#index').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#logout').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

     $('#sign_up').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

          $('#sign_in').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

               $('#easy').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

                    $('#search').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


                    $('#write').css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });



  });













</script>

app/views/top/search.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href ="/assets/css/reset.css" rel ="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>

<style>
body {margin: 0 auto;}
body {text-align: center;}
body {padding-bottom: 30px;}
strong{color: white;}
strong{font-size: 18px;}
strong{display: inline-table;}
.header {padding-top: 30px;}
.header {background-color: yellowgreen;}
.header {height:50px;}


.green_box {width: 200px;}
.green_box {height:30px;}
.green_box {background-color: green;}

.green_box {font-size: 18px;}
.green_box {margin: 0 auto;}

.fix {padding-left: 35px;}





.kaminari {font-size: 24px;}
#box {background-color: orange;}
#box {padding-top: 20px;}
#box {height: 30px;}
#box {margin: :0 auto;}

.kaminari {font-size: 24px;}


.all {padding-right: 35px;}

</style>
<div class ="header">
  <a href ="/pre_search_test"><strong id ="fun">過去問を投稿する</strong></a>　　<a href ="/tests/index"><strong id ="easy">過去問一覧</strong></a>　　<a href ="/"><strong id ="index">注目授業ランキング</strong></a>　　<a href ="/pre_search"><strong>授業を検索</strong></a>　　<a href ="/pre_search_review"><strong>授業評価を見る</strong></a>　　<a href ="/pre_search_entry"><strong>授業評価を書く</strong></a>　<% if user_signed_in? %> <a href ="/users/sign_out"><strong>ログアウト</strong></a> <% else %> <a href ="/users/sign_up"><strong>新規登録</strong></a>　　<a href ="/users/sign_in"><strong>ログイン</strong>
  <% end %>
    </div> 

<div class ="all">

<% if @products.blank? %>
<h3>"<%= params[:keyword] %>"の検索結果はありません</h3>
<h3><a href ="/pre_search">他のキーワードで検索する</h3></a>
<% else %> 

<div class ="main">
<div class = "list">
<h3 id ="left">"<%= params[:keyword] %>"の検索結果を表示しています。</h3>
<% @products.each do |product| %>
  <ul>
    <h3><a href= "/show/<%= product.id %>"><span><%= product.title %>  <%= product.professer %>先生</li></span>
  </ul>
  <% end %>
  </div>
  <div class ="kaminari">
   <%= paginate @products %>
  </div>
</div>

<% end %>

<div class ="fix">
<h4><div class ="green_box"><p><%= link_to '検索画面に戻る', pre_search_path, :style=>"color:white;" %></p></h4></div>
<div class ="fix"><h4 id ="left"><div class ="green_box"><p><%= link_to 'ランキングへ', root_path, :style=>"color:white;" %></p></h4></div></h4>
</h4>

</div>


<script>
$(function(){

  $('strong').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });






});

</script>

app/views/top/search_4.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href ="/assets/css/reset.css" rel ="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>

<style>
body {margin: 0 auto;}
body {text-align: center;}
body {padding-bottom: 30px;}
strong{color: white;}
strong{font-size: 18px;}
strong{display: inline-table;}
.header {padding-top: 30px;}
.header {background-color: yellowgreen;}
.header {height:50px;}
.fix {padding-left: 35px;}
#fun {color: pink;}
#fun {border-bottom: 2px ridge orange;}

.kaminari {font-size: 24px;}


.all {padding-right: 35px;}

.green_box {width: 200px;}
.green_box {height:30px;}
.green_box {background-color: green;}

.green_box {font-size: 18px;}
.green_box {margin: 0 auto;}



</style>
<div class ="header">
    <a href ="/pre_search_test"><strong id ="fun">過去問を投稿する</strong></a>　　<a href ="/tests/index"><strong id ="easy">過去問一覧</strong></a>　　<a href ="/"><strong id ="index">注目授業ランキング</strong></a>　　<a href ="/pre_search"><strong id ="search">授業を検索</strong></a>　　<a href ="/pre_search_review"><strong id ="review">授業評価を見る</strong></a>　　<a href ="/pre_search_entry"><strong id ="write">授業評価を書く</strong></a>　<% if user_signed_in? %> <a href ="/users/sign_out"><strong id ="logout">ログアウト</strong></a> <% else %> <a href ="/users/sign_up"><strong id ="sign_up">新規登録</strong></a>　　<a href ="/users/sign_in"><strong id ="sign_in">ログイン</strong>
  <% end %>
    </div> 


<div class ="all">
<% if @products.blank? %>
<h3>"<%= params[:keyword] %>"の検索結果はありません</h3>
<h3><a href ="/pre_search_entry">他のキーワードで検索する</a></h3>

<% else %> 

<div class ="main">
<div class = "list">
<h3 id ="left">"<%= params[:keyword] %>"の検索結果を表示しています。</h3>
<% @products.each do |product| %>
  <ul>
    <h3><a href= "/test/<%= product.id %>"><span><%= product.title %> <%= product.professer %>先生</li></span>
  </ul>
  <% end %>
  </div>
  <div class ="kaminari">
   <%= paginate @products %>
  </div>
</div>

<% end %>

<div class ="fix">
<h4><div class ="green_box"><p><%= link_to '検索画面に戻る', pre_search_path, :style=>"color:white;" %></p></h4></div>
<div class ="fix"><h4 id ="aa"><div class ="green_box"><p><%= link_to 'ランキングへ', root_path, :style=>"color:white;" %></p></h4></div></h4>
</div>

</div>

<script>


$(function(){

  $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#fun').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#write').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#logout').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

     $('#sign_up').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

          $('#sign_in').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

               $('#easy').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

                    $('#search').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


  $('#index').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });










});

</script>

app/views/top/thank_you.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href ="/assets/css/reset.css" rel ="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>

<style>
body {margin: 0 auto;}
body {text-align: center;}
strong{color: white;}
strong{font-size: 18px;}
strong{display: inline-table;}
.header {padding-top: 30px;}
.header {background-color: yellowgreen;}
.header {height:50px;}


.green_box {width: 200px;}
.green_box {height:30px;}
.green_box {background-color: green;}
.green_box {color: white;}
.green_box {font-size: 18px;}
.green_box {margin: 0 auto;}





.main1 {padding-top: 30px;}

#red {font-size: 30px;}
#red {color: red}



</style>


<script type="text/javascript">

function validate(f)
{
  if(f.easy.value == "") 
  {
    alert("楽単度を入力してください");
    return false;
  }
  else if(f.fun.value =="");
  {
    alert("面白さを入力してください");
    return false;
  }
  else if(f.report.value =="");
  {
    alert("レポートの有無を入力してください");
    return false;
  }
  else if(f.attendence.value == "")
  {
    alert("出席の有無を入力してください");
    return false;
  }
  else if(f.test.value =="")
  {
    alert("テストの有無を入力してください");
    return false;
  }
  else if(f.review.value =="")
  
    alert("コメントを何かお書きください")
    return false;
  }
  return true;
}


$(function(){

  $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#fun').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#review').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


    $('#index').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

    $('#logout').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

     $('#sign_up').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

          $('#sign_in').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

               $('#easy').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });

                    $('#search').hover(function(){
    $(this).css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });

    }, function(){
    $(this).css({
      'color': 'white',
      'border-bottom' : 'none'
    });
  });


                    $('#write').css({
      'color' : 'pink',
      'border-bottom' : '2px ridge orange'
    });



  });











</script>


<div class ="header">

  <a href ="/pre_search_test"><strong id ="fun">過去問を投稿する</strong></a>　　<a href ="/tests/index"><strong id ="easy">過去問一覧</strong></a>　　<a href ="/"><strong id ="index">注目授業ランキング</strong></a>　　<a href ="/pre_search"><strong id ="search">授業を検索</strong></a>　　<a href ="/pre_search_review"><strong id ="review">授業評価を見る</strong></a>　　<a href ="/pre_search_entry"><strong id ="write">授業評価を書く</strong></a>　<% if user_signed_in? %> <a href ="/users/sign_out"><strong id ="logout">ログアウト</strong></a> <% else %> <a href ="/users/sign_up"><strong id ="sign_up">新規登録</strong></a>　　<a href ="/users/sign_in"><strong id ="sign_up">ログイン</strong>
  <% end %>
  </div>

<img src ="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSWJlc4q_64Wuqi7kcTgA4FZB0pVTnxvclAav0Ru0IIXY-tTMQkXArrFJOVZQ" width="300px">




<h4 id ="aaa"><div class ="green_box"><p><%= link_to '授業を検索する', pre_search_path, :style=>"color:white;" %></p></h4></div>

 <h4 id ="aaa"><div class ="green_box"><p><%= link_to 'ランキングへ', root_path, :style=>"color:white;" %></p></h4></div>


  <footer>
  </footer>